---
language: python
python: "2.7"
before_install:
  - sudo apt-get update --assume-yes -qq
  - sudo apt-get install --assume-yes -qq python-apt python-pycurl
install:
  - sudo pip install ansible
script:
  - ansible --version
  - ansible-playbook --inventory-file tests/hosts --syntax-check tests/playbook.yml
  - ansible-playbook --inventory-file tests/hosts --connection=local -vvvv tests/playbook.yml
