---
# tasks file for ansible-gitea
- name: Assert supported distribution
  tags: gitea
  assert:
    that: ansible_distribution + '-' + ansible_distribution_major_version in gitea_supported_distributions

- name: Ensure sha256sum is available
  tags: gitea
  assert:
    that: gitea_sha256sum[gitea_version] is defined

- name: Create gitea user
  tags: gitea
  become: true
  user:
    name: "{{ gitea_username }}"
    home: "{{ gitea_home }}"
    system: true

- name: Install prerequisites
  tags: gitea
  become: true
  package:
    name: git
    state: present

- name: Include datapersitency tasks
  tags: gitea
  include: "{{ role_path }}/../silpion.lib/tasks/datapersistency.yml"
  vars:
    util_persistent_data_path_remote_owner: "{{ gitea_username }}"
    util_persistent_data_path_remote_group: "{{ gitea_username }}"
    util_persistent_data_path_remote_mode: "0755"

- name: Create directorys
  tags: gitea
  become: true
  with_items:
    - "{{ gitea_home ~ '/custom' }}"
    - "{{ gitea_home ~ '/custom/data' }}"
    - "{{ gitea_logdir }}"
    - "{{ gitea_config_dir }}"
  file:
    state: directory
    path: "{{ item.path|default(item) }}"
    owner: "{{ item.owner|default(gitea_username) }}"
    group: "{{ item.group|default(gitea_username) }}"
    mode: 0755

- name: Download gitea
  tags: gitea
  include: "{{ role_path }}/../silpion.lib/tasks/get_url.yml"
  vars:
    url: "https://dl.gitea.io/gitea/{{ gitea_version }}/gitea-{{ gitea_version }}-linux-amd64"
    filename: "{{ gitea_filename }}"
    sha256sum: "{{ gitea_checksum }}"

- name: Copy gitea
  tags: gitea
  include: "{{ role_path }}/../silpion.lib/tasks/copy.yml"
  vars:
    filename: "{{ gitea_filename }}"
    mode: "0755"

- name: Link config
  tags: gitea
  become: true
  file:
    state: link
    src: "{{ gitea_config_dir }}"
    dest: "{{ gitea_home }}/custom/conf"

- name: Deploy config
  tags: gitea
  notify: service gitea restart
  become: true
  template:
    src: "{{ gitea_appini_template }}"
    dest: "{{ gitea_config_dir }}/app.ini"
    owner: 0
    group: "{{ gitea_username }}"
    mode: 0640

- name: Deploy unitfiles
  tags: gitea
  notify: service gitea restart
  become: true
  register: registered_unitfiledeployment
  template:
    src: gitea.service.j2
    dest: /etc/systemd/system/gitea.service

- name: Reload unitfiles
  tags: gitea
  become: true
  when: registered_unitfiledeployment|changed
  command: systemctl daemon-reload

- name: Deploy facts
  tags: gitea
  include: "{{ role_path }}/../silpion.lib/tasks/localfacts.yml"
  vars:
    template: facts.j2
    namespace: gitea

- name: Ensure gitea service is enabled and started
  tags: gitea
  become: true
  notify: Ensure gitea is running
  service:
    state: started
    enabled: true
    name: gitea

- name: Help user
  debug:
    msg: >
      Find your gitea at http://{{ gitea_domain }}:3000
      To create an initial user, you need to temporarily set
      DISABLE_REGISTRATION=false in {{ gitea_config_dir }}/app.ini
