---
# handlers file for ansible-gitea
- name: service gitea restart
  tags: gitea
  become: true
  notify: Ensure gitea is running
  service:
    name: gitea
    state: restarted

- name: Ensure gitea is running
  tags: gitea
  changed_when: false
  become: true
  command: systemctl status gitea
